Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):

zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],

ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].

Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy

Полученные значения должны быть равны.

Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas.

In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [3]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [4]:
MX = zp.mean()
MY = ks.mean()
cov = (zp * ks).mean() - MX * MY
cov

9157.839999999997

In [5]:
cov = ((zp - MX) * (ks - MY)).mean()
cov

9157.84

In [6]:
cov = np.cov(zp, ks)
cov

array([[ 3882.93333333, 10175.37777778],
       [10175.37777778, 33854.32222222]])

In [7]:
cov = ((zp - MX) * (ks - MY)).sum() / ks.shape[0] - 1
cov

9156.84

In [10]:
corr = cov / (zp.std() * ks.std())
corr

0.8873931816570412

In [25]:
dict = {'zp': zp, 'ks': ks}
df = pd.DataFrame(dict)
df

zp   ks
0   35  401
1   45  574
2  190  874
3  200  919
4   40  459
5   70  739
6   54  653
7  150  902
8  120  746
9  110  832

In [26]:
df.corr()

zp       ks
zp  1.00000  0.88749
ks  0.88749  1.00000

In [27]:
np.corrcoef(zp, ks)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

Измерены значения IQ выборки студентов,
обучающихся в местных технических вузах:

131, 125, 115, 122, 131, 115, 107, 99, 125, 111.

Известно, что в генеральной совокупности IQ распределен нормально.

Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [28]:
samples = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])

In [29]:
mean_s = samples.mean()
std_s = samples.std()
print(mean_s, std_s)

118.1 10.004498987955369


In [31]:
n = len(samples)
n

10

Из таблицы квантилей:

In [33]:
t = 2.2622

Далее используя имеющиеся данные по формуле считаем доверительный интервал:

In [34]:
(mean_s - t * std_s / np.sqrt(n), mean_s + t * std_s / np.sqrt(n))

(110.94307703411864, 125.25692296588134)

Известно, что рост футболистов в сборной распределен нормально

с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27,

среднее выборочное составляет 174.2. Найдите доверительный интервал для 

математического
ожидания с надежностью 0.95.

In [35]:
disp = 25
n = 27
mean_s = 174.2
std_s = np.sqrt(disp)
std_s

5.0

In [36]:
samples = np.random.normal(mean_s, std_s, size = 27)
samples

array([171.6732553 , 177.56064114, 174.06889917, 172.74276597,
       175.84625941, 177.23449282, 178.84554679, 184.52218335,
       174.22155549, 181.07590848, 178.61650927, 173.61599811,
       164.77814312, 167.79508141, 172.42331578, 178.22806324,
       182.26530335, 169.73480007, 182.26161009, 168.19258032,
       182.95893032, 178.75945704, 172.0860472 , 170.17665846,
       168.79269305, 183.03386668, 173.30002437])

По сути дела последнее действие сверху бесполезно, дальше просто снова подставляем значения в формулу и получаем доверительный интервал:

Из таблицы квантилей t будет равен:


In [37]:
t = 2.0555

In [38]:
(mean_s - t * std_s / np.sqrt(n), mean_s + t * std_s / np.sqrt(n))

(172.2220942028012, 176.17790579719878)